---
name: "Test"

on: push

jobs:
  pytest:
    name: "Test"
    runs-on: "ubuntu-latest"
  
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install linux dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[linux]
    - name: Install pytest
      run: |
        pip install pytest
    - name: Test
      run: python -m pytest
